modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory
license = "AZURUNE License" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "delicate_dyes" #mandatory
version = "2.0.0" #mandatory
displayName = "Delicate Dyes" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile="icon.png" #optional
credits="${credits}" #optional
authors = "${mod_author}" #optional
description = '''test''' #mandatory (Supports multiline text)

[[mixins]]
config = "delicate_dyes.mixins.json"

[[mixins]]
config = "delicate_dyes.neoforge.mixins.json"

[[dependencies.delicate_dyes]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[21.1.80,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.delicate_dyes]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[1.21.1, 1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.delicate_dyes]]
modId="runiclib"
type="required"
versionRange="[4.3.7,)"
ordering="AFTER"
side="BOTH"